# Generated by Django 4.1.6 on 2023-02-09 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('weekday', models.CharField(max_length=20, null=True)),
                ('hour', models.TimeField(auto_now=True)),
                ('day', models.DateField(default=datetime.date(2023, 2, 9), null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
